<?php

function messenger_cron()
{
  mediamosa_debug::log('Start ' . __METHOD__, array(), 'Toon');
  $scheduler = new scheduler();
  $scheduler->round_up_jobs();

  // Testing purposes
  $server = new server();

  // create a new cURL resource
  //$ch = curl_init();

  //// set URL and other appropriate options
  //curl_setopt($ch, CURLOPT_URL, "http://www.example.com/");
  //curl_setopt($ch, CURLOPT_HEADER, 0);

  //// grab URL and pass it to the browser
  //curl_exec($ch);

  // close cURL resource, and free up system resources
  //curl_close($ch);

}

